---

- file:
    path: "{{ user_scripts_dir }}"
    state: directory

- name: Download Amazon CloudWatch Monitoring Scripts
  get_url: url=http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip dest={{ user_scripts_dir }}/CloudWatchMonitoringScripts-1.2.2.zip

- name: Unarchive zip
  unarchive:
    src: "{{ user_scripts_dir  }}/CloudWatchMonitoringScripts-1.2.2.zip"
    dest: "{{ user_scripts_dir  }}"
    remote_src: True

- name: Delete zip file
  file: path={{ user_scripts_dir }}/CloudWatchMonitoringScripts-1.2.2.zip state=absent
