- debug:
    msg: "Setting up user - {{ user }}"

- name: Set up users
  user:
    name: '{{ user }}'
    shell: /bin/bash
    remove: yes
    state: absent
    force: yes
  tags:
    - users

- name: Set up multiple authorized keys
  authorized_key:
    user: '{{ user }}'
    key: "{{ lookup('file', 'public_keys/{{ user }}') }}"
