---
- hosts: frontend:frontend_staging
  vars:
    user_scripts_dir: /home/ec2-user/scripts
    monitoring_scripts_dir: "{{ user_scripts_dir }}/aws-scripts-mon"
  become: yes
  become_method: sudo
  remote_user: ec2-user

  tasks:
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - perl-Switch
        - perl-DateTime
        - perl-Sys-Syslog
        - perl-LWP-Protocol-https
        - perl-Digest-SHA
        - perl-URI
        - perl-libwww-perl
        - perl-MIME-tools
        - perl-Crypt-SSLeay
        - perl-XML-LibXML
        - unzip
        - curl

    - stat: "path={{ monitoring_scripts_dir }}"
      register: monitoring_scripts_dir_check

    - name: Setup Amazon CloudWatch Memory Monitoring Script
      import_tasks: '../tasks/cloudwatch_memory_monitoring.yml'
      vars:
        scripts_dir: "{{ user_scripts_dir }}"
      when: monitoring_scripts_dir_check.stat.exists == False

    - cron:
        name: Report Memory Metrics
        cron_file: /etc/crontab
        minute: "*"
        hour: "*"
        day: "*"
        user: root
        job: "{{ monitoring_scripts_dir }}/mon-put-instance-data.pl --mem-used --from-cron --mem-avail --swap-used --mem-used-incl-cache-buff"

    - name: Create security-updates script for cron.daily
      copy:
        src: ./scripts/security-updates
        dest: /etc/cron.daily
        owner: root
        group: root
        mode: 0755

    - cron:
        name: Run Daily Cron
        cron_file: /etc/crontab
        minute: "12"
        hour: "{{ groups['frontend'].index(inventory_hostname) + 2 }}"
        day: "*"
        user: root
        job: "run-parts /etc/cron.daily"
