---
- hosts: frontend:frontend_staging
  vars:
    scripts_dir: /home/ec2-user/scripts
  become: yes
  become_method: sudo
  remote_user: ec2-user

  tasks:
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - perl-Switch
        - perl-DateTime
        - perl-Sys-Syslog
        - perl-LWP-Protocol-https
        - perl-Digest-SHA
        - perl-URI
        - perl-libwww-perl
        - perl-MIME-tools
        - perl-Crypt-SSLeay
        - perl-XML-LibXML
        - unzip
        - curl

    - stat: path={{ scripts_dir }}
      register: scripts_dir_check

    - name: Setup Amazon CloudWatch Memory Monitoring Script
      import_tasks: '../tasks/cloudwatch_memory_monitoring.yml'
      vars:
        user_scripts_dir: "{{ scripts_dir }}"
      when: scripts_dir_check.stat.exists == False
